esphome:
  name: esp-phongngu
  friendly_name: ESP_PHONGNGU

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DX5zSKVNHCdNtyzpCYfpmBGPjUrdmd4ZIbpp1SVrdn8="

ota:
  - platform: esphome
    password: "bd76dc49cd529ee33277fe05e89ab36a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Phongngu Fallback Hotspot"
    password: "JTAhWdPaSFu4"

captive_portal:

globals:
  - id: servo_state
    type: bool
    restore_value: yes
    initial_value: 'true'

servo:
  - id: servo_phongngu
    output: pwm_output
    min_level: 2.5%
    max_level: 12.5%

output:
  - platform: ledc
    id: pwm_output
    pin: GPIO23
    frequency: 50 Hz
  
switch:
  - platform: gpio
    pin: 
      number: GPIO25
      inverted: False
    name: "LightBulb"
  - platform: gpio
    pin: 
      number: GPIO26
      inverted: False
    name: "Fan"
  
  - platform: template
    name: "Cửa sổ"
    id: cua_so
    optimistic: False   # Bắt buộc để dashboard hiển thị trạng thái thật
    icon: "mdi:window-open"
    
    lambda: |-
      return id(servo_state);

    turn_on_action:
      - logger.log: "Mở cửa sổ (SG90 xoay 180°)"
      - servo.write:
          id: servo_phongngu
          level: 1.0
      - lambda: 'id(servo_state) = true;'

    turn_off_action:
      - logger.log: "Đóng cửa sổ (SG90 về 0°)"
      - servo.write:
          id: servo_phongngu
          level: 0.0
      - lambda: 'id(servo_state) = false;'

sensor:
  - platform: dht
    pin: GPIO32
    model: DHT11
    temperature: 
      name: "Temperature"
    humidity: 
      name: "Humidity"
    update_interval: 15s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO33
      mode: INPUT
      inverted: True   # tuỳ loại cảm biến, nếu gặp vật cản đọc 0 thì đảo lại
    name: "IR Obstacle Sensor"
    device_class: motion
    filters:
      - delayed_on: 300ms
      - delayed_off: 500ms


