esphome:
  name: esp-phongkhach
  friendly_name: ESP_PHONGKHACH

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rEuVn1VEaHcqmJompd7KWHQwCJeJ3nh+mKc5+H0ooCo="

ota:
  - platform: esphome
    password: "34307ba01f93862759859d8c18a78fc2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Phongkhach Fallback Hotspot"
    password: "y23EFM21MLog"

captive_portal:

globals:
  - id: servo_state
    type: bool
    restore_value: yes
    initial_value: 'false'

servo:
  - id: servo_phongkhach
    output: pwm_output
    min_level: 2.5%
    max_level: 12.5%

output:
  - platform: ledc
    id: pwm_output
    pin: GPIO23
    frequency: 50 Hz

i2c:
  sda: 21
  scl: 22
  scan: True

sensor:
  - platform: bme280_i2c
    temperature:
      name: "BME280 Temperature"
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 15s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT
      inverted: True   # tuỳ loại cảm biến, nếu gặp vật cản đọc 0 thì đảo lại
    name: "IR Obstacle Sensor"
    device_class: motion

switch:
  - platform: gpio
    pin:
      number: GPIO19
      inverted: False
    name: "LIght Bulb"
  
  - platform: gpio
    pin: 
      number: GPIO18
      inverted: False
    name: "Fan"
  
  - platform: template
    name: "Cửa sổ"
    id: cua_so
    optimistic: False   # Bắt buộc để dashboard hiển thị trạng thái thật
    icon: "mdi:window-open"
    
    lambda: |-
      return id(servo_state);

    turn_on_action:
      - logger.log: "Mở cửa sổ (SG90 xoay 180°)"
      - servo.write:
          id: servo_phongkhach
          level: 1.0
      - lambda: 'id(servo_state) = true;'

    turn_off_action:
      - logger.log: "Đóng cửa sổ (SG90 về 0°)"
      - servo.write:
          id: servo_phongkhach
          level: 0.0
      - lambda: 'id(servo_state) = false;'
  


